import { assertEqual, assertTrue } from "./assert.js";
import { buildOpaPolicy, exportFilenameRego } from "../js/export/opaExport.js";
import { FRAMEWORKS, GATE_THRESHOLDS } from "../js/config/criteria.js";

// No OPA binary is available at test time, so this checks the generated Rego text
// is well-formed and correct by string content — actual `opa eval` syntax validation
// is a documented manual-verification caveat (see DECISIONS.md).
const baseline = FRAMEWORKS.find((f) => f.id === "baseline");
const rego = buildOpaPolicy(baseline);

assertTrue(rego.includes("package dor.gatekeeper"), "policy declares the dor.gatekeeper package");
assertTrue(rego.includes("import rego.v1"), "policy imports rego.v1 (modern syntax)");
assertTrue(rego.includes(`approved_threshold := ${GATE_THRESHOLDS.APPROVED}`), "policy embeds the approved threshold");
assertTrue(rego.includes(`conditional_threshold := ${GATE_THRESHOLDS.CONDITIONAL}`), "policy embeds the conditional threshold");
assertTrue(rego.includes('gate_decision := "APPROVED"'), "policy derives APPROVED gate_decision");
assertTrue(rego.includes('gate_decision := "CONDITIONAL"'), "policy derives CONDITIONAL gate_decision");
assertTrue(rego.includes('gate_decision := "BLOCKED"'), "policy derives BLOCKED gate_decision");

const denyRuleCount = (rego.match(/deny contains msg if \{/g) || []).length;
assertEqual(denyRuleCount, 2, "policy declares both deny rules (BLOCKED score, unresolved High-severity gap)");
assertTrue(rego.includes('gate_decision == "BLOCKED"'), "first deny rule checks for a BLOCKED gate");
assertTrue(rego.includes('gap.severity_gov == "High"'), "second deny rule checks for an unresolved High-severity gap");

// Every framework produces a valid policy, not just the baseline.
for (const framework of FRAMEWORKS) {
  const policy = buildOpaPolicy(framework);
  assertTrue(policy.includes(`# Generated by dor-gatekeeper — ${framework.label}`), `[${framework.id}] policy header names the framework`);
}

assertEqual(
  exportFilenameRego("baseline", "abc-123"),
  "baseline_abc-123_dor_policy.rego",
  "Rego filename is slugified frameworkId + assessment_id"
);
