import { GATE_THRESHOLDS } from "../config/criteria.js";
import { slugify } from "./jsonExport.js";

// Emits a real, syntactically valid Rego module (modern `rego.v1` syntax) usable
// as-is with `opa eval`/`conftest` — not illustrative text. Evaluated against a
// dor-gatekeeper JSON export (see jsonExport.js) as `input`.
export function buildOpaPolicy(framework) {
  const lines = [];

  lines.push("package dor.gatekeeper");
  lines.push("");
  lines.push("import rego.v1");
  lines.push("");
  lines.push(`# Generated by dor-gatekeeper — ${framework.label}`);
  lines.push(`# Evaluate with: opa eval -d <this file> -i <dor-gatekeeper JSON export> "data.dor.gatekeeper.deny"`);
  lines.push("");
  lines.push(`approved_threshold := ${GATE_THRESHOLDS.APPROVED}`);
  lines.push(`conditional_threshold := ${GATE_THRESHOLDS.CONDITIONAL}`);
  lines.push("");
  lines.push("overall_score := input.overall_score");
  lines.push("");
  lines.push('gate_decision := "APPROVED" if overall_score >= approved_threshold');
  lines.push("");
  lines.push('gate_decision := "CONDITIONAL" if {');
  lines.push("\toverall_score >= conditional_threshold");
  lines.push("\toverall_score < approved_threshold");
  lines.push("}");
  lines.push("");
  lines.push('gate_decision := "BLOCKED" if overall_score < conditional_threshold');
  lines.push("");
  lines.push("# Deny merge if the gate is BLOCKED");
  lines.push("deny contains msg if {");
  lines.push('\tgate_decision == "BLOCKED"');
  lines.push('\tmsg := sprintf("DoR gate BLOCKED: overall_score %.1f is below the conditional threshold of %d", [overall_score, conditional_threshold])');
  lines.push("}");
  lines.push("");
  lines.push("# Deny merge if any High-severity gap remains unresolved, regardless of overall score");
  lines.push("deny contains msg if {");
  lines.push("\tsome pillar in input.pillars");
  lines.push("\tsome gap in pillar.gaps");
  lines.push('\tgap.severity_gov == "High"');
  lines.push('\tmsg := sprintf("Unresolved High-severity gap: %s (%s)", [gap.description, gap.category_tag])');
  lines.push("}");
  lines.push("");

  return lines.join("\n");
}

export function exportFilenameRego(frameworkId, assessmentId) {
  return `${slugify(frameworkId)}_${assessmentId}_dor_policy.rego`;
}
